### ISSUE TITLE
Provide an example, how to use it on organic groups

### ISSUE THREAD

**Issue by schoenid** [backdrop-contrib/prepopulate#1]
This is a question:

I'm trying to create an automatic selection of a group while creating a new organic group content.
The structure in HTML looks as follows:

<select multiple="multiple" name="og_group_ref[und][0][default][]" id="edit-og-group-ref-und-0-default" class="form-select">
    <option value="_none">- None -</option>
    <option value="7">Erzähler-Gruppe</option>
    <option value="9">Maler-Gruppe</option>
    <option value="10">Musiker-Gruppe</option>
    <option value="15">Tänzer-Gruppe</option>
</select>

So I've created a view with the Content: Title of the group, I want to create new content in.
[(Group node from OG membership) Content: Title](https://backdrop/admin/structure/views/nojs/config-item/og_current_user/block/field/title_1)
This gives me the groups title, if I'm on the groups page URL, as example "Erzähler-Gruppe".
Then I've tried to Rewrite Results for this field: "Create new book ..." and to output the field as a link:
Link path: /node/add/book?edit[og_group_ref][und][0][value]=Title

So this or something similar should open the book edit page (it does), but with marked group (it does not ...).
I've tried several possibilities and combinations, without success.

Link path: /node/add/book?edit[og_group_ref]=Title
Link path: /node/add/book?edit[og_group_ref][und][0][default]=Title
Link path: /node/add/book?edit[og_group_ref][und][0][default][value]=Title
Link path: /node/add/book?edit[og_group_ref][value]=Title
Link path: /node/add/book?edit[og_group_ref][default]=Title
Link path: /node/add/book?edit[og_group_ref][default][value]=Title
and more ...

Could someone help here, please?
Many people would be thankful.

Best Regards

**Comment by olafgrabienski** [comment]
@schoenid Try to add the ‚NID‘ (Node ID) to the link path. It worked for me following the steps below.

  - Add a views block, content of type Group, Field: Nid, and rewrite the field to:
    `<a href="/node/add/post?edit[og_group_ref][und][0][default]=[nid]" title="Add a post to this group">Add post</a>`
  - Add a Contextual filter to the view: "Content: NID", Provide default value: "Content ID from URL".
  - Place the views block in the sidebar of the Group layout.
  
  Does that work for you? (You need to adapt the example slightly.)
  
  See also https://github.com/backdrop-contrib/og/issues/45#issuecomment-1058244419.

**Comment by schoenid** [comment]
Great !!!

I'm using the following views configuration, to allow it to be displayed only in a group with valid membership:

RELATIONSHIPS
- OG membership: OG membership from User account
- (OG membership from user) OG membership: Group Node from OG membership

CONTEXTUAL FILTERS
- (OG membership from user) OG membership: Group ID  ->  set to "Provide default value" and "Content ID from URL"

FILTER CRITERIA
- User account: Active (Active)
- User account: Current (Yes)

FIELDS
- (Group node from OG membership) Content: Title
Settings "Rewrite results":
Text: "Create new Book ..."
Checked: "Output this field as a link"
Link path: /node/add/book?edit[og_group_ref][und][0][default]=%1

This works 👍 

As I found further below in the field settings the "Replacement patterns" I was able to configure the view for different configurations of the Groups audience field:
For Lists:  /node/add/book?edit[og_group_ref][und][0][default]=%1
For Checkboxes:  /node/add/book?edit[og_group_ref][und][0][default][%1]=%1
For Autocomplete (Tags style):  /node/add/book?edit[og_group_ref][und][0][default]=[title_1]

@olafgrabienski  👍  Thank you very much !!!

**Comment by laryn** [comment]
@schoenid Would you be willing to add a page to the Wiki with this information for others to find more easily?

**Comment by schoenid** [comment]
@laryn Yes, I would do that, if I would have an edit permission. Unfortunately I don't have it.

**Comment by laryn** [comment]
@schoenid  thanks! I think I just opened up the wiki to edits. Let me know if you still have trouble with it.

**Comment by schoenid** [comment]
@laryn Thank you too.
I've created a detailed example, how to find and apply the correct settings to a view, for the creation of a new groups content, using Prepopulate, to fill in the groups association. I hope, everything is fine.
