### ISSUE TITLE
Should prepopulate work in Webform to populate a radio button from the url?

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/prepopulate#2]
I'm trying to use this to preselect a radio button select option in a webform.  Found the input name, crafted what should work according to the wiki.
`form/398/contact?submitted[who_is_your_message_for]=2`

No selection made.  Any thing I'm doing wrong or is this not likely to work as its a different type of form?

**Comment by yorkshire-pudding** [comment]
After reading [this drupal issue](https://www.drupal.org/project/prepopulate/issues/582724) I tried:

`form/398/contact?edit[submitted][who_is_your_message_for]=2`

This didn't work, but `form/398/contact?edit[submitted][name]=bob` does work so I think the gap in my understanding is how to make this work with a radio button.  It's manually entered in the form rather than being a taxonomy reference.

I tried to extrapolate from the wiki and tried this:
`contact?edit[submitted][who_is_your_message_for][und]=2` but no joy

**Comment by yorkshire-pudding** [comment]
Ok after looking at [this drupal issue](https://www.drupal.org/project/prepopulate/issues/1772148)

I tried
`/form/398/contact?edit[submitted][who_is_your_message_for][2]=2`

and this worked.

Updated the title to make it more meaningful to anyone else searching for this.

For reference, the `[submitted]` bit is from the name attribute of each of the radio buttons in the group:
`name="submitted[who_is_your_message_for]"`
but it has to go into square brackets.
`[2]` and `=2` refer to the value attribute of the individual radio button:
`value="2"`

**Comment by laryn** [comment]
Thanks, I copypasted the last comment into the Wiki: https://github.com/backdrop-contrib/prepopulate/wiki/Usage-with-webform
