### ISSUE TITLE
Creates empty config but won't import

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/prepopulate#3]
**Steps to reproduce**

1. Install prepopulate on local
2. git the codebase and config (whatever method) to staging on another environment
3. Enable prepopulate on other server
4. run config-import (UI or bee)

**Expected result**
Imports config (or no config for prepopulate given its empty and no config needed)

**Actual result**
Error message: 

```
The configuration "prepopulate.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again
```

Config file (`prepopulate.settings.json`) is:

```json
{
    "_config_name": "prepopulate.settings"
}
```
If delete config from staging then will import.

**Comment by laryn** [comment]
It looks like Coder Upgrade created an empty config file but there is no config in this module. I think we can remove that entire config folder and the `prepopulate_update_1000` update hook.
